-- Additive catalog; existing category IDs and metadata are preserved.
begin;
insert into public.categories(id,name) values('Gaming','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Ação / Aventura','Gaming - Ação / Aventura','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - RPG','Gaming - RPG','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - FPS','Gaming - FPS','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Battle Royale','Gaming - Battle Royale','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - MOBA','Gaming - MOBA','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Estratégia','Gaming - Estratégia','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Simulação','Gaming - Simulação','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Corrida','Gaming - Corrida','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Esportes','Gaming - Esportes','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Sandbox','Gaming - Sandbox','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Terror','Gaming - Terror','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Indie','Gaming - Indie','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Mobile','Gaming - Mobile','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gaming - Retro','Gaming - Retro','Gaming') on conflict(id) do nothing;
insert into public.categories(id,name) values('Música','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Rock','Música - Rock','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Pop','Música - Pop','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Sertanejo','Música - Sertanejo','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Eletrônica','Música - Eletrônica','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Funk','Música - Funk','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Rap / Hip-Hop','Música - Rap / Hip-Hop','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - MPB','Música - MPB','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Lo-fi','Música - Lo-fi','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Instrumental','Música - Instrumental','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - DJ Sets','Música - DJ Sets','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Produção Musical','Música - Produção Musical','Música') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Música - Karaokê','Música - Karaokê','Música') on conflict(id) do nothing;
insert into public.categories(id,name) values('Just Chatting','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - Bate-Papo','Just Chatting - Bate-Papo','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - Perguntas e Respostas','Just Chatting - Perguntas e Respostas','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - Histórias','Just Chatting - Histórias','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - Desafios','Just Chatting - Desafios','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - React','Just Chatting - React','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - Debates','Just Chatting - Debates','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - Comédia','Just Chatting - Comédia','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Just Chatting - Comunidade','Just Chatting - Comunidade','Just Chatting') on conflict(id) do nothing;
insert into public.categories(id,name) values('Criatividade','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Desenho','Criatividade - Desenho','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Design','Criatividade - Design','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Fotografia','Criatividade - Fotografia','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Edição','Criatividade - Edição','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Animação','Criatividade - Animação','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - 3D','Criatividade - 3D','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Artesanato','Criatividade - Artesanato','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Escrita','Criatividade - Escrita','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Moda','Criatividade - Moda','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Criatividade - Produção Criativa','Criatividade - Produção Criativa','Criatividade') on conflict(id) do nothing;
insert into public.categories(id,name) values('Esportes','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Futebol','Esportes - Futebol','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Basquete','Esportes - Basquete','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Vôlei','Esportes - Vôlei','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Automobilismo','Esportes - Automobilismo','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Lutas','Esportes - Lutas','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Skate','Esportes - Skate','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Ciclismo','Esportes - Ciclismo','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Corrida','Esportes - Corrida','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Fitness','Esportes - Fitness','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Esportes - Esportes Radicais','Esportes - Esportes Radicais','Esportes') on conflict(id) do nothing;
insert into public.categories(id,name) values('Tecnologia','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Programação','Tecnologia - Programação','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Hardware','Tecnologia - Hardware','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Inteligência Artificial','Tecnologia - Inteligência Artificial','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Ciência e Tech','Tecnologia - Ciência e Tech','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Cibersegurança','Tecnologia - Cibersegurança','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Linux e Open Source','Tecnologia - Linux e Open Source','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Robótica','Tecnologia - Robótica','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Ciência de Dados','Tecnologia - Ciência de Dados','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Desenvolvimento de Jogos','Tecnologia - Desenvolvimento de Jogos','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - Notícias Tech','Tecnologia - Notícias Tech','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Tecnologia - DevOps','Tecnologia - DevOps','Tecnologia') on conflict(id) do nothing;
insert into public.categories(id,name) values('Podcasts','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Conversas','Podcasts - Conversas','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Entrevistas','Podcasts - Entrevistas','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Notícias','Podcasts - Notícias','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Entretenimento','Podcasts - Entretenimento','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Educação','Podcasts - Educação','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Esportes','Podcasts - Esportes','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Tecnologia','Podcasts - Tecnologia','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Podcasts - Cultura','Podcasts - Cultura','Podcasts') on conflict(id) do nothing;
insert into public.categories(id,name) values('IRL','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Viagens','IRL - Viagens','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Eventos','IRL - Eventos','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Vida Cotidiana','IRL - Vida Cotidiana','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Exploração','IRL - Exploração','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Bastidores','IRL - Bastidores','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Compras','IRL - Compras','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Natureza','IRL - Natureza','IRL') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('IRL - Gastronomia','IRL - Gastronomia','IRL') on conflict(id) do nothing;
insert into public.categories(id,name) values('Educação','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Matemática','Educação - Matemática','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Física','Educação - Física','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Química','Educação - Química','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Biologia','Educação - Biologia','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - História','Educação - História','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Geografia','Educação - Geografia','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Idiomas','Educação - Idiomas','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Vestibular e ENEM','Educação - Vestibular e ENEM','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Programação','Educação - Programação','Educação') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Educação - Estudo ao Vivo','Educação - Estudo ao Vivo','Educação') on conflict(id) do nothing;
insert into public.categories(id,name) values('Ciência','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Astronomia','Ciência - Astronomia','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Espaço','Ciência - Espaço','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Física','Ciência - Física','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Biologia','Ciência - Biologia','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Química','Ciência - Química','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Meio Ambiente','Ciência - Meio Ambiente','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Experimentos','Ciência - Experimentos','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Ciência - Divulgação Científica','Ciência - Divulgação Científica','Ciência') on conflict(id) do nothing;
insert into public.categories(id,name) values('Gastronomia','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Culinária','Gastronomia - Culinária','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Receitas','Gastronomia - Receitas','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Confeitaria','Gastronomia - Confeitaria','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Churrasco','Gastronomia - Churrasco','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Comida de Rua','Gastronomia - Comida de Rua','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Reviews','Gastronomia - Reviews','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Cozinha Internacional','Gastronomia - Cozinha Internacional','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Gastronomia - Desafios Culinários','Gastronomia - Desafios Culinários','Gastronomia') on conflict(id) do nothing;
insert into public.categories(id,name) values('Filmes e Séries','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Filmes e Séries - Filmes','Filmes e Séries - Filmes','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Filmes e Séries - Séries','Filmes e Séries - Séries','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Filmes e Séries - Análises','Filmes e Séries - Análises','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Filmes e Séries - Teorias','Filmes e Séries - Teorias','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Filmes e Séries - Premiações','Filmes e Séries - Premiações','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Filmes e Séries - Bastidores','Filmes e Séries - Bastidores','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Filmes e Séries - Trailers e Novidades','Filmes e Séries - Trailers e Novidades','Filmes e Séries') on conflict(id) do nothing;
insert into public.categories(id,name) values('Anime e Cultura Pop','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Anime e Cultura Pop - Anime','Anime e Cultura Pop - Anime','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Anime e Cultura Pop - Mangá','Anime e Cultura Pop - Mangá','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Anime e Cultura Pop - Quadrinhos','Anime e Cultura Pop - Quadrinhos','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Anime e Cultura Pop - Cosplay','Anime e Cultura Pop - Cosplay','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Anime e Cultura Pop - Colecionáveis','Anime e Cultura Pop - Colecionáveis','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Anime e Cultura Pop - Cultura Geek','Anime e Cultura Pop - Cultura Geek','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Anime e Cultura Pop - Eventos','Anime e Cultura Pop - Eventos','Anime e Cultura Pop') on conflict(id) do nothing;
insert into public.categories(id,name) values('Negócios','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Negócios - Empreendedorismo','Negócios - Empreendedorismo','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Negócios - Marketing','Negócios - Marketing','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Negócios - Finanças Pessoais','Negócios - Finanças Pessoais','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Negócios - E-commerce','Negócios - E-commerce','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Negócios - Carreira','Negócios - Carreira','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Negócios - Produtividade','Negócios - Produtividade','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Negócios - Startups','Negócios - Startups','Negócios') on conflict(id) do nothing;
insert into public.categories(id,name) values('Lifestyle','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Lifestyle - Moda','Lifestyle - Moda','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Lifestyle - Beleza','Lifestyle - Beleza','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Lifestyle - Fitness','Lifestyle - Fitness','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Lifestyle - Bem-estar','Lifestyle - Bem-estar','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Lifestyle - Casa e Decoração','Lifestyle - Casa e Decoração','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Lifestyle - Pets','Lifestyle - Pets','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Lifestyle - Rotina','Lifestyle - Rotina','Lifestyle') on conflict(id) do nothing;
insert into public.categories(id,name) values('Jogos de Mesa','Jogos de Mesa') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Jogos de Mesa - RPG de Mesa','Jogos de Mesa - RPG de Mesa','Jogos de Mesa') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Jogos de Mesa - Board Games','Jogos de Mesa - Board Games','Jogos de Mesa') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Jogos de Mesa - Card Games','Jogos de Mesa - Card Games','Jogos de Mesa') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Jogos de Mesa - Xadrez','Jogos de Mesa - Xadrez','Jogos de Mesa') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Jogos de Mesa - D&D','Jogos de Mesa - D&D','Jogos de Mesa') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Jogos de Mesa - Miniaturas','Jogos de Mesa - Miniaturas','Jogos de Mesa') on conflict(id) do nothing;
insert into public.categories(id,name,parent_id) values('Jogos de Mesa - Wargames','Jogos de Mesa - Wargames','Jogos de Mesa') on conflict(id) do nothing;
commit;
